// Motivational gym quotes
export const gymQuotes = [
    "The only bad workout is the one that didn't happen!",
    "Your body can stand almost anything. It's your mind you have to convince.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Don't wish for it, work for it!",
    "Success starts with self-discipline.",
    "The hard days are the best because that's when champions are made.",
    "Push yourself because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't come from what you do occasionally, it comes from what you do consistently.",
    "Wake up with determination. Go to bed with satisfaction.",
    "Do something today that your future self will thank you for.",
    "Little progress is still progress.",
    "Believe in yourself and all that you are.",
    "You are stronger than you think!",
    "Make yourself proud!",
    "The body achieves what the mind believes.",
    "Strive for progress, not perfection.",
    "Every workout counts!",
    "Today's workout is tomorrow's warm-up.",
    "Discipline is doing what needs to be done, even if you don't want to do it.",
    "Motivation is what gets you started. Habit is what keeps you going.",
    "A one-hour workout is only 4% of your day. No excuses.",
    "Sweat is just fat crying.",
    "Fitness is not about being better than someone else. It’s about being better than you were yesterday.",
    "Respect your body. It’s the only one you get.",
    "It never gets easier, you just get better.",
    "Your health is your wealth.",
    "Train insane or remain the same.",
    "Muscles are torn in the gym, fed in the kitchen, and built in bed.",
    "Sore today, strong tomorrow.",
    "Don't stop when you're tired. Stop when you're done.",
    "Excuses don't burn calories.",
    "Action is the foundational key to all success.",
    "All progress takes place outside the comfort zone.",
    "Don't count the days, make the days count.",
    "Energy and persistence conquer all things.",
    "Exercise is a celebration of what your body can do. Not a punishment for what you ate.",
    "Fall seven times, stand up eight.",
    "First they laugh. Then they copy. Don't give up.",
    "Go the extra mile. It's never crowded.",
    "Good things come to those who sweat.",
    "Hard work beats talent when talent doesn't work hard.",
    "Hustle for that muscle.",
    "I don't stop when I'm tired, I stop when I'm done.",
    "If it doesn't challenge you, it doesn't change you.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "It's not about having time. It's about making time.",
    "Look in the mirror. That's your competition.",
    "Making excuses burns zero calories per hour.",
    "No pain, no gain. Shut up and train.",
    "Nothing will work unless you do.",
    "Obsessed is just a word the lazy use to describe the dedicated.",
    "Of course it’s hard. It’s supposed to be hard. If it were easy, everyone would do it.",
    "Pain is weakness leaving the body.",
    "Rome wasn't built in a day, but they worked on it every single day.",
    "Strength does not come from physical capacity. It comes from an indomitable will.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "Take care of your body. It's the only place you have to live.",
    "The difference between the impossible and the possible lies in a person's determination.",
    "The only place where success comes before work is in the dictionary.",
    "There are no shortcuts to any place worth going.",
    "Think about why you started.",
    "To give anything less than your best is to sacrifice the gift.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
    "What hurts today makes you stronger tomorrow.",
    "When you feel like quitting, think about why you started.",
    "You don't have to be great to start, but you have to start to be great.",
    "Your body hears everything your mind says.",
    "Your only limit is you.",
    "Be the hardest worker in the room.",
    "Don't decrease the goal. Increase the effort.",
    "Success is what comes after your stop making excuses.",
    "The clock is ticking. Are you becoming the person you want to be?",
    "You can have results or excuses. Not both.",
    "Champions keep playing until they get it right.",
    "Clear your mind of can't.",
    "Get comfortable with being uncomfortable.",
    "Invest in yourself. It pays the best interest.",
    "It's a slow process, but quitting won't speed it up.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "Slow progress is better than no progress.",
    "Stay positive, work hard, make it happen.",
    "The body achieves what the mind believes.",
    "The pain of discipline is far less than the pain of regret.",
    "Trust the process.",
    "Work hard in silence. Let success be your noise.",
    "You didn't come this far to only come this far.",
];

export function getRandomQuote(): string {
    return gymQuotes[Math.floor(Math.random() * gymQuotes.length)];
}

export function getDayName(): string {
    const days = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
    return days[new Date().getDay()];
}
